# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_img', models.CharField(max_length=255)),
                ('g_price', models.FloatField(default=1)),
                ('is_delete', models.BooleanField(default=False)),
                ('g_unit', models.CharField(default='500g', max_length=20)),
                ('g_kucun', models.CharField(max_length=10)),
                ('g_click', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ttsx_goods',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20)),
                ('t_img', models.CharField(max_length=256, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ttsx_type',
            },
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeModel'),
        ),
    ]
