# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('is_counted', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_create_time', models.DateTimeField(auto_now_add=True)),
                ('o_is_payed', models.BooleanField(default=False)),
                ('o_total', models.FloatField(default=2, max_length=10)),
                ('o_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
            options={
                'db_table': 'ttsx_order',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('totalprice', models.FloatField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsModel')),
            ],
            options={
                'db_table': 'ttsx_sales',
            },
        ),
        migrations.AddField(
            model_name='ordergoodmodel',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderModel'),
        ),
    ]
