# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgoodsmodel',
            name='in_cart',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cartgoodsmodel',
            name='is_select',
            field=models.BooleanField(default=0),
        ),
    ]
